### ISSUE TITLE
Cannot destructure property `precision` of `undefined` or `null`

### ISSUE THREAD

**Issue by kevva** [shrpne/pretty-num#1]
If you don't provide any options to this module, it'll throw due to [this](https://github.com/shrpne/pretty-num/blob/master/src/index.js#L13) line which expects an object to destructure as the second argument.

Could just set a default parameter to prevent this.

**Comment by shrpne** [comment]
Thank you for your report!
It fixed in [v0.1.1](https://github.com/shrpne/pretty-num/commit/41a3153e033a01dd9d3902dccf0da5f1b1fbf02e)
