### ISSUE TITLE
[Feature request] Add decimalSeparator property

### ISSUE THREAD

**Issue by vtaits** [shrpne/pretty-num#3]
Hi. Thousands and decimals can be separated only with `"."`.

https://github.com/shrpne/pretty-num/blob/5d71eaee16f32d01ef3370481fb00da34407b9dc/src/pad-zeros-to-fixed.js#L28

But the standard of my country standard is `","`. It will be very cool if I can configure it natively.

**Comment by shrpne** [comment]
Hi! Nice idea!
PR is welcome :)

**Comment by vtaits** [comment]
https://github.com/shrpne/pretty-num/pull/4

**Comment by shrpne** [comment]
Released under [v0.4.0](https://www.npmjs.com/package/pretty-num/v/0.4.0)
